/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 film.gltf 
Author: Bendar Multimedia (https://sketchfab.com/bendar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-film-slate-or-clapper-f971698c983d4256a269424e88b17872
Title: Black film slate or clapper
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/film.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Empty001_4" position={[2.264, 2.389, 1.746]} rotation={[0.124, 0, 0]}>
                <group name="Cube002_3" position={[-0.004, 0.067, -1.398]} rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
                  <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['Material.003']} />
                </group>
              </group>
              <group name="Cube_0" position={[2.922, 1.181, -0.047]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube001_1" position={[2.89, 3.088, -0.015]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.003']} />
              </group>
              <group name="Cube003_2" position={[1.995, 2.499, 1.396]} scale={[0.457, 0.393, 0.381]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.002']} />
              </group>
              <group name="Cylinder_5" position={[2.438, 2.386, 1.737]} rotation={[-0.028, 0.028, -1.57]} scale={[0.033, 0.008, 0.033]}>
                <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder001_6" position={[2.438, 2.151, 1.737]} rotation={[-0.028, 0.028, -1.57]} scale={[0.033, 0.008, 0.033]}>
                <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder002_7" position={[2.438, 2.151, 1.06]} rotation={[-0.028, 0.028, -1.57]} scale={[0.033, 0.008, 0.033]}>
                <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cube005_8" position={[2.523, 2.499, 1.396]} scale={[-0.457, 0.393, 0.381]}>
                <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials['Material.002']} />
              </group>
              <group name="Cylinder003_9" position={[2.08, 2.386, 1.737]} rotation={[-0.028, 0.028, 1.572]} scale={[-0.033, 0.008, 0.033]}>
                <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder004_10" position={[2.08, 2.151, 1.737]} rotation={[-0.028, 0.028, 1.572]} scale={[-0.033, 0.008, 0.033]}>
                <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials['Material.004']} />
              </group>
              <group name="Cylinder005_11" position={[2.08, 2.151, 1.06]} rotation={[-0.028, 0.028, 1.572]} scale={[-0.033, 0.008, 0.033]}>
                <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials['Material.004']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/film.gltf')
